version: '3.7'
volumes: 
    mysql_data1:
    mysql_data2:
    wordpress_data1:
    wordpress_data2:
   

services: 
    database1:
        image: mysql:latest
        volumes: 
            - mysql_data1:/var/lib/mysql
        restart: always
        environment: 
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_db
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: 123456

    database2:
        image: mysql:latest
        volumes: 
            - mysql_data2:/var/lib/mysql
        restart: always
        environment: 
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_db
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: 123456

    wordpress1:
        depends_on: 
            - database1
        image: wordpress:latest
        volumes: 
            - wordpress_data1:/var/www/html
        ports: 
            - "5001:80"
        restart: always
        environment: 
            WORDPRESS_DB_HOST: database1
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: 123456
            WORDPRESS_DB_NAME: wordpress_db

    wordpress2:
        depends_on:
            - database2

        image: wordpress:latest
        volumes:
            - wordpress_data2:/var/www/html
        ports:
            - "5002:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: database2
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: 123456
            WORDPRESS_DB_NAME: wordpress_db  


    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
